# -*- coding: utf-8 -*-
"""Capstone_BR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dyRDkx_Oz-9OsneKz9UvY7R7uBEmMimr

#**Exploring Global Matneral Health data:Lifetime Risk of Maternal Death**

#Bethania Robertson | Biomedical Data Science - Capstone Project | 10/20/2025

###This notebook analyzed maternal health data, specifically analyzing Maternal Mortality Ratio (MMR), maternal deaths and liftetime risk (LTR) from 2000 to 2023. It calculates and visualally represents trends globally, regionally and by some specific countries. The analysis aims to reveal patterns and the disparties found in maternal health worldwide.

#####Methods included in this report are but are not limited to computation of percentage change and variability for each variable, correlation analysis to examine the variables relationships and multiple linear regression to assess the combined efffect of maternal deaths on LTR and MMR to better understand the patterns in maternal health

###Raw Data set was utilized from UNICEF Data from *"Trends in maternal mortality 2000-2023"*

Accessing a dataset stored in Google Drive to analysis maternal health. Exploring the data available to use before data manipulation
"""

#Imports for data manipulation
import pandas as pd

#Mounting Data Set into Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

#Load the Excel file
file_path = '/content/drive/My Drive/MMRandLTR.xlsx' #link
xls = pd.ExcelFile(file_path)

#Output available sheet names
print("Sheet names:", xls.sheet_names)

"""#Exploring Maternal Mortality Ratio

##Exploring Global Average MMR Overtime

Exploring Maternal Mortality Ratio - Country Data
"""

#Display Data Structure
mmr_country = xls.parse('MMR_country_level', skiprows=4)
mmr_country.head()

"""Mean MMR by Country-data Worldwide"""

#Imports for plotting and visualization
import matplotlib.pyplot as plt

#Calculating average MMR
years = [str(year) for year in range(2000,2023)] #list of the years
mean_mmr_country = mmr_country[years].mean() #average MMR value for each country

#Plotting
plt.figure(figsize=(10,6))
plt.plot(years, mean_mmr_country, marker='o', linestyle='-', color='b') #Plotting avergae MMR across country data
plt.xticks(rotation=60)
plt.title('Mean MMR by Country-data Worldwide Overtime')
plt.xlabel('Year')
plt.ylabel('Mean MMR')
plt.grid(True)
plt.show()

"""##Exploring Country Level MMR Analysis Overtime

Maternal Mortality Ratio (MMR) Trends for Selected Countries
"""

#List of countries
countries_to_plot = ['Afghanistan', 'Bahamas', 'Brazil','Canada', 'Cuba', 'Fiji', 'Haiti','Nepal', 'Poland', 'Togo', 'Zambia']

#PLotting
plt.figure(figsize=(14, 8))

#Lopping through each country for their MMR
for country in countries_to_plot:
    country_data = mmr_country[mmr_country['Country'] == country][years].T #row for country and the column year
    plt.plot(years, country_data.values.flatten(), marker='o', label=country) #countries MMR overtime
plt.title('Maternal Mortality Ratio (MMR) Trends for Selected Countries (2000-2023)')
plt.xlabel('Year')
plt.ylabel('MMR')
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""##Exploring Regional MMR Analysis Overtime

Exploring Maternal Mortality Ratio - Region Data
"""

mmr_region = xls.parse('MMR_regional_level', skiprows=5)
mmr_region.head()

"""Average Maternal Mortality Ratio (MMR) by Region"""

#List of years
years = [str(year) for year in range(2000, 2023)]

#Grouping each year and calculating mean MMR for each
region_mmr = mmr_country.groupby('UNICEF Programme Region')[years].mean()

#PLotting
plt.figure(figsize=(14, 8))
for region in region_mmr.index: #Looping through the different countries in each region
    plt.plot(years, region_mmr.loc[region], marker='o', label=region)
plt.title('Average Maternal Mortality Ratio (MMR) by UNICEF Programme Region (2000-2023)')
plt.xlabel('Year')
plt.ylabel('Average MMR')
plt.xticks(rotation=45)
plt.legend(title='Region', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Specific Regions MMR Trends overlayed with Respective Countries"""

'''
East Asia and the Pacific
'''

#specific region
region = 'East Asia and the Pacific'

#visualizing specific countries from that region
countries_in_region = mmr_country[mmr_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_mmr.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = mmr_country[mmr_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'MMR Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('MMR')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

'''
Europe and Central Asia
'''

#specific region
region = 'Europe and Central Asia'

#visualizing specific countries from that region
countries_in_region = mmr_country[mmr_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_mmr.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = mmr_country[mmr_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'MMR Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('MMR')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

'''
Eastern and Southern Africa
'''
#specific region
region = 'Eastern and Southern Africa'

#visualizing specific countries from that region
countries_in_region = mmr_country[mmr_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_mmr.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = mmr_country[mmr_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'MMR Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('MMR')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

"""Linear Regression on Regional Average MMR to Visualize Annual trends"""

#Imports
from sklearn.linear_model import LinearRegression
import numpy as np

#Years
X = np.array([int(year) for year in years]).reshape(-1, 1)

#Storage for Slope (rate of change) per region
region_slopes = {}

#Plotting
num_regions = len(region_mmr.index) #setting up one grid per region
fig, axs = plt.subplots(nrows=num_regions, ncols=1, figsize=(12, 4*num_regions), sharex=True)

#Keeps Consistent Looping
if num_regions == 1:  #one region? axis will not be an array
    axs = [axs]

#Looping over region to fit linear regression
for i, region in enumerate(region_mmr.index):
    y_vals = region_mmr.loc[region, years].values.flatten() #flattening MMR values for current region
    mask = ~np.isnan(y_vals) #filters out NaN values
    X_clean = X[mask] #filtered years with available data
    y_clean = y_vals[mask] #data without NaNs

    #Regression with enough data
    if len(y_clean) > 1:
        model = LinearRegression()
        model.fit(X_clean, y_clean) #fitting model
        slope = model.coef_[0] #extracting slope
        region_slopes[region] = slope #slope storage

        #Plotting MMR Values Overtime
        axs[i].plot([int(y) for y in years], y_vals, marker='o', label='Actual MMR')#Individual Data points
        axs[i].plot([int(y) for y in years], model.predict(X), linestyle='--', color='red', label='Trend line')#Regression line
        axs[i].set_title(f"{region} (Slope: {slope:.2f} MMR/year)")
        axs[i].set_ylabel('MMR')
        axs[i].grid(True)
        axs[i].legend()

plt.xlabel('Year')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Slope to DataFrame
region_slopes_df = pd.DataFrame.from_dict(region_slopes, orient='index', columns=['MMR Yearly Slope'])
region_slopes_df = region_slopes_df.sort_values('MMR Yearly Slope')

#Outputs
print("Yearly MMR trends by region (negative slope = decrease in MMR):")
print(region_slopes_df)

"""Percentage and Variability within Regional Data - MMR"""

#Defining Variables
start_year = '2000'
end_year = '2022'

#Calculating percentage change - MMR
percent_change = ((region_mmr[end_year] - region_mmr[start_year]) / region_mmr[start_year]) * 100
percent_change = percent_change.round(2)

#Ooutputs of percentage change
print("Percentage change in average MMR by region (2000 to 2023):")
print(percent_change.sort_values())

#Plotting
plt.figure(figsize=(12, 6))
percent_change.sort_values().plot(kind='bar', color='skyblue') #percentage change
plt.title('Percentage Change in Average MMR by Region (2000 to 2023)')
plt.ylabel('Percentage Change (%)')
plt.xlabel('Region')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

#Calculating Variability - MMR
regions = mmr_country['UNICEF Programme Region'].unique()
variability_dict = {}

#Looping through regions
for region in regions:
    region_countries = mmr_country[mmr_country['UNICEF Programme Region'] == region] #specific countries
    std_devs = region_countries[years].std(axis=0) #STD
    avg_std_dev = std_devs.mean() #Average STD
    variability_dict[region] = avg_std_dev #Varibaility of Avergae STD
variability_df = pd.Series(variability_dict).round(2).sort_values()

#Outputs of Varibaility
print("\nAverage standard deviation of MMR within regions (variability across countries):")
print(variability_df)

#Plotting
plt.figure(figsize=(12, 6))
variability_df.plot(kind='bar', color='coral')
plt.title('Average Standard Deviation of MMR Within Regions (2000-2022)') #variability
plt.ylabel('Standard Deviation of MMR')
plt.xlabel('Region')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""#Exploring Maternal Deaths

Exploring Maternal Death - Country Data
"""

#Display Data Structure
maternal_deaths_country = pd.read_excel(file_path, sheet_name='Maternal deaths_country_level', skiprows=4)
maternal_deaths_country.head()

"""Global Matneral Deaths Overtime

&

Regional Maternal Deaths Overtime
"""

#Years
years = [str(year) for year in range(2000, 2024)]

#Turn NaNs to 0
maternal_deaths_country[years] = maternal_deaths_country[years].fillna(0)

#Calculating global and regions total maternal deaths per year
global_maternal_deaths = maternal_deaths_country[years].sum() #global
region_maternal_deaths = maternal_deaths_country.groupby('UNICEF Programme Region')[years].sum() #regional

#Plotting - Global
plt.figure(figsize=(12, 6))
plt.plot(years, global_maternal_deaths.values, marker='o', color='red') #global average
plt.title('Global Total Maternal Deaths Over Time (2000-2023)')
plt.xlabel('Year')
plt.ylabel('Total Maternal Deaths')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

#Plotting - Regional
plt.figure(figsize=(14, 8))
for region in region_maternal_deaths.index: #Looping over each region
    plt.plot(years, region_maternal_deaths.loc[region], label=region)
plt.title('Maternal Deaths by Region Over Time (2000-2023)')
plt.xlabel('Year')
plt.ylabel('Total Maternal Deaths')
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Specific Regions Maternal Death Trends overlayed with Respective Countries"""

'''
Western and Central Africa
'''

#region
region = 'West and Central Africa'

#visualizing specific countries from that region
countries_in_region = maternal_deaths_country[maternal_deaths_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_maternal_deaths.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = maternal_deaths_country[maternal_deaths_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'Maternal Deaths Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('Maternal Deaths')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

'''
Europe and Central Asia
'''
#region
region = 'Europe and Central Asia'

#visualizing specific countries from that region
countries_in_region = maternal_deaths_country[maternal_deaths_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_maternal_deaths.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = maternal_deaths_country[maternal_deaths_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'Maternal Deaths Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('Maternal Deaths')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()
'''
East Asia and the Pacific
'''
#region
region = 'East Asia and the Pacific'

#visualizing specific countries from that region
countries_in_region = maternal_deaths_country[maternal_deaths_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_maternal_deaths.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = maternal_deaths_country[maternal_deaths_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'Maternal Deaths Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('Maternal Deaths')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

"""Linear Regression on Regional Maternal Death to Visualize Annual trends"""

#Years
X = np.array([int(year) for year in years]).reshape(-1, 1)

#Storage for Slope(rate of change) by regions
region_slopes = {}

#One plot per region
num_regions = len(region_maternal_deaths.index)
fig, axs = plt.subplots(nrows=num_regions, ncols=1, figsize=(12, 4*num_regions), sharex=True)

#Ensurings if there is only 1 regions that the axis is not an array
if num_regions == 1:
    axs = [axs]

for i, region in enumerate(region_maternal_deaths.index): #looping through each region
    y_vals_raw = region_maternal_deaths.loc[region, years].values.flatten() #extracting maternal death values
    y_vals = pd.to_numeric(y_vals_raw, errors='coerce')

    #Masking non-Nan values
    mask = ~np.isnan(y_vals)
    X_clean = X[mask]
    y_clean = y_vals[mask]

    if len(y_clean) > 1:
        model = LinearRegression() #linear regression
        model.fit(X_clean, y_clean) #fitting the model
        slope = model.coef_[0]
        region_slopes[region] = slope

#Plotting
        axs[i].plot([int(y) for y in years], y_vals, marker='o', label='Actual Maternal Deaths') #plotting raw data points
        axs[i].plot([int(y) for y in years], model.predict(X), linestyle='--', color='red', label='Trend line') #plotting regression line

        axs[i].set_title(f"{region} (Slope: {slope:.2f} deaths/year)")
        axs[i].set_ylabel('Maternal Deaths')
        axs[i].grid(True)
        axs[i].legend()

plt.xlabel('Year')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Adding the slopes from the storage to DF
region_slopes_df = pd.DataFrame.from_dict(region_slopes, orient='index', columns=['Maternal Deaths Yearly Slope'])
region_slopes_df = region_slopes_df.sort_values('Maternal Deaths Yearly Slope')

#Outputs
print("Yearly maternal death trends by region (negative slope = decrease in deaths):")
print(region_slopes_df)

"""Percentage and Variability within Regional Data - Maternal Death"""

#Defining Variables
start_year = '2000'
end_year = '2023'

#Calculating percentage change in average maternal deaths per region (from 2000 to 2023)
percent_change = ((region_maternal_deaths[end_year] - region_maternal_deaths[start_year]) / region_maternal_deaths[start_year]) * 100
percent_change = percent_change.round(2)

#Outputs
print("Percentage change in average maternal deaths by region (2000 to 2023):")
print(percent_change.sort_values())

#Plotting
plt.figure(figsize=(12, 6))
percent_change.sort_values().plot(kind='bar', color='skyblue') #percentage change - maternal deaths
plt.title('Percentage Change in Average Maternal Deaths by Region (2000 to 2023)')
plt.ylabel('Percentage Change (%)')
plt.xlabel('Region')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

#Calculating variability of country maternal deaths within each region per year
regions = maternal_deaths_country['UNICEF Programme Region'].unique()
variability_dict = {}

for region in regions: #looping through regions
    region_countries = maternal_deaths_country[maternal_deaths_country['UNICEF Programme Region'] == region] #specific countries
    std_devs = region_countries[years].apply(pd.to_numeric, errors='coerce').std(axis=0) #STD across countries overtime
    avg_std_dev = std_devs.mean() #Average STD
    variability_dict[region] = avg_std_dev

#adding to DF
variability_df = pd.Series(variability_dict).round(2).sort_values()

#Outputs
print("\nAverage standard deviation of maternal deaths within regions (variability across countries):")
print(variability_df)

#Plotting
plt.figure(figsize=(12, 6))
variability_df.plot(kind='bar', color='coral') #variability - maternal deaths
plt.title('Average Standard Deviation of Maternal Deaths Within Regions (2000-2023)')
plt.ylabel('Standard Deviation of Maternal Deaths')
plt.xlabel('Region')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""#Exploring Lifetime Risk of Maternal Death (LTR)"""

#Display Data Structure
ltr_country = pd.read_excel(file_path, sheet_name='LTR_country_level', skiprows=4)
ltr_country.head()

"""Global Average LTR Overtime"""

#Calculating average LTR
years = [str(year) for year in range(2000, 2023)]
global_ltr = ltr_country[years].mean()

#Plotting
plt.figure(figsize=(12, 6))
plt.plot(years, global_ltr.values, marker='o', color='green') #LTR
plt.title('Global Average Lifetime Risk of Maternal Deaths Over Time (2000-2023)')
plt.xlabel('Year')
plt.ylabel('Average Lifetime Risk of Maternal Deaths')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""Average LTR by Region"""

#grouped regions and calculated mean LTR per year
region_ltr = ltr_country.groupby('UNICEF Programme Region')[years].mean()

#Plotting
plt.figure(figsize=(14,8))
for region in region_ltr.index: #lopping through the regions overtime
    plt.plot(years, region_ltr.loc[region], label=region) #LTR
plt.title('Regional Average Lifetime Risk of Maternal Death (LTR) Over Time')
plt.xlabel('Year')
plt.ylabel('LTR')
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Specific Regions LTR Trends overlayed with Respective Countries"""

'''
Western and Central Africa
'''

#region
region = 'West and Central Africa'

#visualizing specific countries from that region
countries_in_region = ltr_country[ltr_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_ltr.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = ltr_country[ltr_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'Lifetime Risk of Maternal Death Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('Lifetime Risk of Maternal Death (%)')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

'''
Europe and Central Asia
'''

#region
region = 'Europe and Central Asia'

#visualizing specific countries from that region
countries_in_region = ltr_country[ltr_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_ltr.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = ltr_country[ltr_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'Lifetime Risk of Maternal Death Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('Lifetime Risk of Maternal Death (%)')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

'''
East Asia and the Pacific
'''

#region
region = 'East Asia and the Pacific'

#visualizing specific countries from that region
countries_in_region = ltr_country[ltr_country['UNICEF Programme Region'] == region]['Country'].tolist()

#Plotting
plt.figure(figsize=(14, 8))
plt.plot(years, region_ltr.loc[region], label=f'{region} Average', linewidth=3, color='black')  #regional average
for country in countries_in_region:
    country_data = ltr_country[ltr_country['Country'] == country][years].T
    plt.plot(years, country_data.values.flatten(), label=country, alpha=0.5)
plt.title(f'Lifetime Risk of Maternal Death Trends for {region} Countries Compared to Regional Average')
plt.xlabel('Year')
plt.ylabel('Lifetime Risk of Maternal Death (%)')
plt.xticks(rotation=45) #helping with the bunchiness of the x-axis
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
plt.tight_layout()
plt.show()

"""Linear Regression on LTRto Visualize Annual trends"""

#Years
X = np.array([int(year) for year in years]).reshape(-1, 1)

#Storage for Slope (rate of change) for each region
region_slopes = {}

#One plot per region
num_regions = len(region_ltr.index)
fig, axs = plt.subplots(nrows=num_regions, ncols=1, figsize=(12, 4*num_regions), sharex=True)

#Ensuring if there is only 1 region, the axis will not be an array
if num_regions == 1:
    axs = [axs]

for i, region in enumerate(region_ltr.index): #looping through the regions
    y_vals_raw = region_ltr.loc[region, years].values.flatten() #flattening and extracting LTR values
    y_vals = pd.to_numeric(y_vals_raw, errors='coerce')
    mask = ~np.isnan(y_vals) #masking non-Nan values
    X_clean = X[mask]
    y_clean = y_vals[mask]

    if len(y_clean) > 1:
        model = LinearRegression() #linear regression
        model.fit(X_clean, y_clean) #fitting model
        slope = model.coef_[0]
        region_slopes[region] = slope

#Plotting
        axs[i].plot([int(y) for y in years], y_vals, marker='o', label='Actual LTR') #raw data points
        axs[i].plot([int(y) for y in years], model.predict(X), linestyle='--', color='red', label='Trend line') #regression line

        axs[i].set_title(f"{region} (Slope: {slope:.5f} LTR/year)")
        axs[i].set_ylabel('Lifetime Risk of Maternal Death') #LTR
        axs[i].grid(True)
        axs[i].legend()

plt.xlabel('Year')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Adding slopes in storage to DF
region_slopes_df = pd.DataFrame.from_dict(region_slopes, orient='index', columns=['LTR Yearly Slope'])
region_slopes_df = region_slopes_df.sort_values('LTR Yearly Slope')

#Outputs
print("Yearly LTR trends by region (negative slope = decrease in lifetime risk):")
print(region_slopes_df)

"""Percentage and Variability within Regional Data - LTR"""

#Defining Variables
start_year = '2000'
end_year = '2022'

#Calculating percentage change in average LTR per region (from 2000 to 2023)
percent_change = ((region_ltr[end_year] - region_ltr[start_year]) / region_ltr[start_year]) * 100
percent_change = percent_change.round(2)

#Outputs
print("Percentage change in average LTR by region (2000 to 2023):")
print(percent_change.sort_values())

#Plotting
plt.figure(figsize=(12, 6))
percent_change.sort_values().plot(kind='bar', color='skyblue') #percentage change - LTR
plt.title('Percentage Change in Average LTR by Region (2000 to 2022)')
plt.ylabel('Percentage Change (%)')
plt.xlabel('Region')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Calculate variability (std deviation) of country LTR within each region per year
regions = ltr_country['UNICEF Programme Region'].unique()
variability_dict = {}

for region in regions: #looping through regions
    region_countries = ltr_country[ltr_country['UNICEF Programme Region'] == region] #specific countries
    std_devs = region_countries[years].apply(pd.to_numeric, errors='coerce').std(axis=0) #STD across countries overtime
    avg_std_dev = std_devs.mean() #average STD
    variability_dict[region] = avg_std_dev

#Adding varibaility to DF
variability_df = pd.Series(variability_dict).round(5).sort_values()

#Outputs
print("\nAverage standard deviation of LTR within regions (variability across countries):")
print(variability_df)

#Plotting
plt.figure(figsize=(12, 6))
variability_df.plot(kind='bar', color='coral') #variability - LTR
plt.title('Average Standard Deviation of LTR Within Regions (2000-2022)')
plt.ylabel('Standard Deviation of LTR')
plt.xlabel('Region')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""#Correlation and Regression through Variables

Correlation
"""

#Putting Years into a list
years_list = [str(y) for y in range(2000, 2023)]

regions = region_mmr.index

#Storage for correlation data
corr_results = pd.DataFrame(index=regions, columns=['MMR-MaternalDeaths', 'MMR-LTR', 'MaternalDeaths-LTR'])

for region in regions: #looping over regions
    #Extraction of series for each variable
    mmr_series = pd.to_numeric(region_mmr.loc[region, years_list], errors='coerce')
    maternal_deaths_series = pd.to_numeric(region_maternal_deaths.loc[region, years_list], errors='coerce')
    ltr_series = pd.to_numeric(region_ltr.loc[region, years_list], errors='coerce')

    #Creation of new DF for correlation
    df = pd.DataFrame({
        'MMR': mmr_series,
        'MaternalDeaths': maternal_deaths_series,
        'LTR': ltr_series
    })

    #Dropping rows with NaNs
    df = df.dropna()

    if len(df) > 1:
        corr_results.loc[region, 'MMR-MaternalDeaths'] = df['MMR'].corr(df['MaternalDeaths'])
        corr_results.loc[region, 'MMR-LTR'] = df['MMR'].corr(df['LTR'])
        corr_results.loc[region, 'MaternalDeaths-LTR'] = df['MaternalDeaths'].corr(df['LTR'])

    #if there is not enough data
    else:
        corr_results.loc[region] = [np.nan, np.nan, np.nan]

#Outputs
print(corr_results.round(2))

"""Visualization of Correlation"""

#imports
import seaborn as sns

#DF for correlation visualizations Prepare a long-format DataFrame for correlation plots
data_list = [] #empty list
for region in region_mmr.index: #looping through regions
    for year in years: #looping through years
        try:
            mmr_val = float(region_mmr.loc[region, year])
            md_val = float(region_maternal_deaths.loc[region, year])
            ltr_val = float(region_ltr.loc[region, year])

            #Ammending DF
            data_list.append({
                'Region': region,
                'Year': int(year),
                'MMR': mmr_val,
                'Maternal_Deaths': md_val,
                'LTR': ltr_val
            })
        except Exception:
            continue  #If data missing/invalid
#adding into DF
df_corr = pd.DataFrame(data_list)

#Plotting
def plot_scatter(x, y, title):
    plt.figure(figsize=(10,6))
    sns.scatterplot(data=df_corr, x=x, y=y, hue='Region')
    sns.regplot(data=df_corr, x=x, y=y, scatter=False, color='black')
    plt.title(title)
    plt.xlabel(x)
    plt.ylabel(y)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

#Plotting
plot_scatter('MMR', 'Maternal_Deaths', 'MMR vs Maternal Deaths by Region') #MMR vs Maternal Deaths
plot_scatter('MMR', 'LTR', 'MMR vs LTR by Region')#MMR vs LTR
plot_scatter('Maternal_Deaths', 'LTR', 'Maternal Deaths vs LTR by Region') #Maternal Deaths vs LTR

"""Multiple Regression"""

#Imports
import statsmodels.api as sm

#Storage for multiple regression values
multiple_regression_results = {}

for region in df_corr['Region'].unique():
    df_region = df_corr[df_corr['Region'] == region]

    # Make sure there are enough data points
    if len(df_region) > 2:
        #Independent variables
        X = df_region[['LTR', 'Maternal_Deaths']]
        y = df_region['MMR']
        X = sm.add_constant(X) #Constant term
        model = sm.OLS(y, X).fit() #fitting to multiple linear regression

        #Adding to storage
        multiple_regression_results[region] = model.summary()
    else:
        multiple_regression_results[region] = None

#Outputs - per region
for region, summary in multiple_regression_results.items():
    print(f"Multiple Regression Results for {region}:")
    if summary:
        print(summary)
    else:
        print("Not enough data for regression.")
    print("\n" + "="*70 + "\n")